openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Water
    description: Operations about water.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:4000
  - url: https://aquatrack-bd.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
