openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation on how to use the AquaTrack database
tags:
  - name: Water
    description: Operations about water.
  - name: Auth
    description: Operations about user.
servers:
  - url: https://aquatrack-bd.onrender.com
  - url: http://localhost:4000
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/data:
    get:
      $ref: ../swagger/paths/auth/data/get.yaml
    patch:
      $ref: ../swagger/paths/auth/data/patch.yaml
  /auth/count:
    get:
      $ref: ../swagger/paths/auth/count/get.yaml
  /auth/request-reset-email:
    post:
      $ref: ../swagger/paths/auth/request-reset-email/post.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/auth/reset-password/post.yaml
  /auth/data-avatar-load:
    put:
      $ref: ../swagger/paths/auth/data-avatar-load/put.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth/post.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get-oauth-url/get.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    put:
      $ref: ../swagger/paths/water/{id}/put.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/daily/{date}:
    get:
      $ref: ../swagger/paths/water/daily/{date}/get.yaml
  /water/monthly/{month}:
    get:
      $ref: ../swagger/paths/water/monthly/{month}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
